# Generated by Django 6.0.7 on 2026-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=200)),
                ('Age', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='story_image/')),
            ],
        ),
    ]
